/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package municipal;
public class NewHos extends javax.swing.JFrame {

    MunCon mycon;
    public NewHos() {
        initComponents();
        this.setBounds(0, 0, 626,626); 
        mycon=new MunCon();
        String x="SELECT DISTINCT hstate FROM hospital ";
        try
        {
            System.out.println(x);
            mycon.rs=mycon.stm.executeQuery(x);
           while(mycon.rs.next())
           {
               String c=mycon.rs.getString("hstate");
            jComboBox6.addItem(c);
           }
           }catch(Exception e)
        {
                e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Hospital Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 148, 33);

        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 70, 71, 24);

        jLabel3.setText("Type");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 112, 71, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "public", "private" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(139, 160, 85, 20);

        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 238, 61, 25);

        jLabel6.setText("Ward number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(83, 356, 75, 27);

        jLabel5.setText("Building number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(83, 320, 75, 30);

        jLabel7.setText("Area");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(83, 389, 75, 25);

        jLabel20.setText("State  :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(83, 271, 116, 14);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(217, 268, 173, 20);

        jLabel14.setText("City  :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(83, 297, 116, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(217, 325, 173, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(217, 294, 173, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(217, 391, 173, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(217, 356, 173, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(139, 70, 322, 24);

        jLabel8.setText("Employee Details");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 497, 148, 33);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 10, 571, 460);

        jButton1.setText("OK");
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 480, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
          jComboBox5.removeAllItems();

        String x="SELECT DISTINCT hcity FROM hospital WHERE hstate='"+jComboBox6.getSelectedItem().toString()+"' ";
        try
        {
            mycon.rs=mycon.stm.executeQuery(x);
            while(mycon.rs.next())
            {
                String c=mycon.rs.getString("hcity");
                jComboBox5.addItem(c);
            }

        }catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
               

    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
